version: '2'
services:
  builder:
    build: .
    environment:
    - WORKDIR=/workdir
    - BUILDS=/workdir/builds
    - KERNEL_BRANCH=rpi-4.19.y 
    - KERNEL_REPO=https://www.github.com/raspberrypi/linux.git
    volumes:
    - ./builds:/workdir/builds
    privileged: true
